export const PUZZLES = [
  { category: "90s Bollywood Movie", answer: "DILWALE DULHANIA LE JAYENGE" },
  { category: "90s Bollywood Movie", answer: "KUCH KUCH HOTA HAI" },
  { category: "90s Bollywood Movie", answer: "ANDAZ APNA APNA" },
  { category: "90s Bollywood Movie", answer: "BAAZIGAR" },
  { category: "90s Bollywood Movie", answer: "HUM AAPKE HAIN KOUN" },
  { category: "90s Hollywood Movie", answer: "THE MATRIX" },
  { category: "90s Hollywood Movie", answer: "JURASSIC PARK" },
  { category: "90s Hollywood Movie", answer: "TITANIC" },
  { category: "90s Hollywood Movie", answer: "PULP FICTION" },
  { category: "90s Hollywood Movie", answer: "FIGHT CLUB" },
  { category: "90s Sitcom Quote", answer: "HOW YOU DOIN" },
  { category: "90s Sitcom Quote", answer: "YADA YADA YADA" },
  { category: "90s Sitcom Quote", answer: "WE WERE ON A BREAK" },
  { category: "90s Movie Quote", answer: "HASTA LA VISTA BABY" },
  { category: "90s Movie Quote", answer: "SHOW ME THE MONEY" },
  { category: "90s Movie Quote", answer: "YOU CANT HANDLE THE TRUTH" },
  { category: "90s Bollywood Song", answer: "CHAIYYA CHAIYYA" },
  { category: "90s Bollywood Song", answer: "EK DO TEEN" },
  { category: "90s Bollywood Song", answer: "PEHLA NASHA" },
  { category: "90s Bollywood Song", answer: "TU CHEEZ BADI HAI MAST MAST" },
  { category: "90s Pop Song", answer: "SMELLS LIKE TEEN SPIRIT" },
  { category: "90s Pop Song", answer: "BABY ONE MORE TIME" },
  { category: "90s Pop Song", answer: "WANNABE" },
  { category: "90s Pop Song", answer: "MACARENA" },
  { category: "90s Pop Song", answer: "WATERFALLS" },
  { category: "90s Pop Song", answer: "VOGUE" },
  { category: "90s Band", answer: "BACKSTREET BOYS" },
  { category: "90s Band", answer: "SPICE GIRLS" },
  { category: "90s Band", answer: "NIRVANA" },
  { category: "90s Toy", answer: "TAMAGOTCHI" },
  { category: "90s Toy", answer: "FURBY" },
  { category: "90s Tech", answer: "FLOPPY DISK" },
  { category: "90s Tech", answer: "DIAL UP MODEM" }
];
